### ISSUE TITLE
Google Advanced Protection issue?

### ISSUE THREAD

**Issue by JohnLGalt** [kam193/thbrd-signature#2]
I have several Google accounts, both regular and G-Suite accounts, and I've enabled Advanced protection on all of them.

Thankfully, Mozilla Thunderbird is certified to work with Google accounts even if Advanced Protection is enabled.  In that regard, I have 0 issues with getting my mail, sending mail, etc.

I followed the wiki to set up an OAuth for the project I created (named GMail Sig Sync) and copied the OAuth ID in the options page to try to get it to connect, but I'm getting the following:

![GMail Sig Sync](https://user-images.githubusercontent.com/7432512/115967287-ceea2800-a4ff-11eb-8cb0-779971cd828f.png)

When I go to the URL mentioned to visit, I get the following:

![GMail Sig Sync error 02](https://user-images.githubusercontent.com/7432512/115967329-11ac0000-a500-11eb-93f2-7b5a5e894ee8.png)

I can run through the settings of the OAuth, but I followed it pretty closely - only difference was that I was forced to do the Consent screen with scopes *before* I could even add the OAuth Client.

Please let me know anything that I need to provide.

**Comment by kam193** [comment]
Hi!

Thanks for the report!

From the end: please not the URL of Google console is longer than you see in the window. I did a test, looks like you just didn't copy the whole address. 

Anyway, the issue is with the redirect domain. Could you please verify the redirect URL in your Google project? It should looks like this:
![obraz](https://user-images.githubusercontent.com/8472271/115970732-9c165300-a544-11eb-950b-d9051617505a.png)

PS. Not related, but please be aware of the issue https://github.com/kam193/thbrd-signature/issues/1 - I'm going to work on it this week.

**Comment by JohnLGalt** [comment]
Ahhh, it needs a forward slash.  Gotcha.  Trying it now.

Aaaaand - it broke.  This time directly because of Advanced Protection.

![GMail Sig Sync error 03](https://user-images.githubusercontent.com/7432512/115971264-83427900-a515-11eb-9e1f-8b797a024082.png)

I've had plenty of small issues like this with AP enabled, but I cannot disable it for various reasons.  Hence my report.

Anyhoo - this may be a lot tougher to figure out.  I've tried to create a few working API calls and whatnot for a few different programs before, and AP has broken every single one of them.  May need to get a Google Cloud Engineer involved to try to fix it.

**Comment by kam193** [comment]
Yeah, it looks like working with the AP may be difficult. I'm also using the lowest possible permissions request :/ I think it would need a kind of special certification, but I'm struggling with the normal currently

![obraz](https://user-images.githubusercontent.com/8472271/115971537-4c865600-a549-11eb-88d4-fa8915dd404d.png)

**Comment by JohnLGalt** [comment]
Yup.  Had a feeling that AP would get in the way.

Sigh.

You'd think that Google would have a way for its own Cloud to work with its own Advanced Protection.

At any rate - if you need help testing further implementations of this add-on (which I absolutely love the idea of) with both regular Google accounts and G-Suite accounts (across 4 different domains) then let me know - I've been using the GMail web interface for a while but it's gotten old trying to maintain that many accounts via a browser, especially since a single Chrome profile instance only allows for 10 different logins - and I have 4 accounts each for the domains alone ... hence my move to using Thunderbird again.

**Comment by kam193** [comment]
Thank you :) I'm using it mostly with G-Suite accounts, I hope I'll find time to fix the long-time sync issue & force official certification process soon. I was surprised that similar extension didn't exist yet

**Comment by JohnLGalt** [comment]
I was surprised as well.   And since I just started using it and I cannot get it working yet, I haven't had a chance to encounter the long-time sync issue - yet.

Question:  does each Thunderbird profile need its own OAuth set up, or can you use a single one for every account / profile?

because if 1 can be used for many, I could (theoretically) create a new Google / G-Suite account that does not have AP enabled and use that across all the profiles and accounts, right?

**Comment by kam193** [comment]
OAuth/Google accounts are totally independent of Thunderbird profiles/accounts. So yes, you should be able to use 1 OAuth multiple times. Emails don't need to match, extension is always pulling the default signature from the Google Account. Let me know if this workaround works.

**Comment by JohnLGalt** [comment]
I'll give it a shot.  Worth testing at any rate :D

**Comment by JohnLGalt** [comment]
> 
> 
> Ahhh, it needs a forward slash. Gotcha. Trying it now.
> 
> Aaaaand - it broke. This time directly because of Advanced Protection.
> 
> ![GMail Sig Sync error 03](https://user-images.githubusercontent.com/7432512/115971264-83427900-a515-11eb-9e1f-8b797a024082.png)
> 
> I've had plenty of small issues like this with AP enabled, but I cannot disable it for various reasons. Hence my report.
> 
> Anyhoo - this may be a lot tougher to figure out. I've tried to create a few working API calls and whatnot for a few different programs before, and AP has broken every single one of them. May need to get a Google Cloud Engineer involved to try to fix it.

Sorry for the late reply - RL gets in the way sometimes :D

OK, I created a new account that is NOT protected by Advanced Protection, and went through all of the steps to get a new OAuth Client ID (and enabled the free credit in Cloud for the new account).

I got the exact same message as above in the quotation.

So, the presence of Advanced Protection on an account is disabling access to the Signature in GMail, as noted by the documentation that you linked to, which is odd, because it specifically says most non Google apps (unless it is because it is marked as testing?  I really think we need to get a Google Cloud Engineer involved in this discussion).

**Comment by kam193** [comment]
> OK, I created a new account that is NOT protected by Advanced Protection, and went through all of the steps to get a new OAuth Client ID (and enabled the free credit in Cloud for the new account).

Hmm, I don't think credits are needed for OAuth Client ID :)

> I then tried to sync the signature for the newly created account not protected by Advanced Protection. While it connected just fine, it won't actually sync the signature that I created.

When you click on "Sync now" in add-on's preferences, do you see a note "Sync failed at..." with the current timestamp below requested account? And could you try to open the console (see screens below), then click on "Sync now" and show me, what you get?

![obraz](https://user-images.githubusercontent.com/8472271/116067239-426b7100-a689-11eb-9c9d-59c45a159b30.png)
![obraz](https://user-images.githubusercontent.com/8472271/116067494-7777c380-a689-11eb-9c6e-07403096ebaa.png)

I feel like there is something that stopped working recently. I need to investigate, so please give me a while to get into & eventually fix it :)

**Comment by JohnLGalt** [comment]
Yeah, I know the credits are not needed - but another application I used to use that made Google API calls through a Cloud account stopped working a couple of years ago, and I never once thought to point the finger at Advanced Protection, so I'm going to be testing that app as well, seeing if I can get it working again.

As for your addon - yes, exactly, "Sync failed at {current UNIX time}".

Since this is a throwaway account, I can share the console output - How should I send it to you?

**Comment by kam193** [comment]
You can send me the log console log on email kam193@wp.pl. I think I know what is the trouble (I'm looking for the solution now), but I wanted to confirm. I'm expecting you see ` Error: Requires user interaction` in the console.

I see you're using Daily on your previous screens :) Don't need to try on stable, I see the same issue on both versions.

**Comment by JohnLGalt** [comment]
Actually, no.

Email coming.

**Comment by JohnLGalt** [comment]
After working with @kam193 for a few days, I'm closing this issue as ver 2.x solves all issues with Advanced Protection on Google / G_Suite accounts.
