### ISSUE TITLE
OAuth flow broken

### ISSUE THREAD

**Issue by EvyBongers** [kam193/thbrd-signature#3]
I just installed this add-on (latest stable from the Github releases) and when attempting to connect, a window opens for the authentication flow. On this page, Google shows this error:

> # Authorization Error
>
> **Error 400: invalid_request**
>
> Missing required parameter: client_id
>
> [Learn more](http://code.google.com/apis/accounts/docs/OAuth2.html)

**Comment by JohnLGalt** [comment]
Same thing when I reported it:

https://github.com/kam193/thbrd-signature/issues/2

The v2 with the added need for the OAuth Client Secret also filled in makes this work, though.

**Comment by kam193** [comment]
Hi @EvyBongers,
did you follow the instruction about creating own Oauth app (https://github.com/kam193/thbrd-signature/wiki/Registering-own-OAuth-app-in-Google) and set the client id in settings? Currently, the add-on comes without credentials to the Google API.

Anyway, as mentioned, there is the version 2 on the way, which I prepared with huge help from @JohnLGalt. I'd suggest waiting a few days - tomorrow I'll send the v2 to the Thunderbird Add-on portal, so should be available there later this week. It will contain default credentials, so registering own OAuth client in Google should be optional (certification in Google is still on the way; in the worst case they will stop working if Google reject my certification).

**Comment by JohnLGalt** [comment]
@kam193 Oops - sorry!  I thought you had already released it to the public, my bad!

**Comment by kam193** [comment]
New version is sent to review in Thunderbird add-on portal. Should be available to download in a few days. 

The package from Github releases doesn't contain OAuth credentials - if you don't want to register own OAuth app in Google, please wait for v2 in Thunderbird portal :)

**Comment by EvyBongers** [comment]
Ah, that explains a lot @kam193. I had followed the instructions in the README. Hadn't noticed that there was a wiki.

**Comment by kam193** [comment]
Hmm, nice, so I probably need to better expose this information :)

**Comment by kam193** [comment]
@EvyBongers Version 2 with built-in OAuth credentials is for some time in the add-on portal. Did you use it? Is everything working?

**Comment by EvyBongers** [comment]
@kam193 I decided to move away from Thunderbird again, because of too many things just not working well enough, so I haven't tried it anymore.

**Comment by kam193** [comment]
Oh, okay! Did you find any interesting open source, or just privacy friendly & working on Linux email client? My tries to find something ended up with going back to the Thunderbird & researching how to improve it :D
