### ISSUE TITLE
Sync with removed account

### ISSUE THREAD

**Issue by cap1024** [kam193/thbrd-signature#5]
An account was removed from the Google and from the Thunderbird but an extension still try to connect to this account.
There is no possibility to remove a extension's connection to the deleted account.

**Comment by kam193** [comment]
Nice catch, I'll try to find a while to add check if the identity exists in the Thunderbird before sync.

**Comment by kam193** [comment]
The fixed version is already published in the Thunderbird add-ons catalog. Please update and let me know if it works good now.

**Comment by cap1024** [comment]
Checked. Fixed. Thanks!

**Comment by kam193** [comment]
Great! If you wish, let's leave a note on Thunderbird add-on page :)
