### ISSUE TITLE
Signature before quoted text in replies

### ISSUE THREAD

**Issue by hiwigiwi** [kam193/thbrd-signature#7]
In the Google settings, you can choose if you want to include the signature before the quoted text when replying to an email. It would be good if this setting is also taken into account by the plugin.

Right now, for me, whenever I hit "Reply" the previous emails are shown in a thread and the Google signature is amended at the very end of this thread, i.e. at the very bottom of the email. I would want the signature to appear at the top instead, so that I can simply write up my reply in front of the signature.

**Comment by kam193** [comment]
Hey,
The plugin doesn't control where your signature is inserted, this is a responsibility of Thunderbird. And you can set it to be similar to Gmail - just go to the Account settings / Composition and addressing, and choose where to place the signature on replies. This is my setting (the same as you want to achieve):

![image](https://user-images.githubusercontent.com/8472271/224341799-cd3d653e-65aa-4320-82b9-7c01cc1fe2c1.png)
