### ISSUE TITLE
Signatures Not Syncing?

### ISSUE THREAD

**Issue by LinuxAndCoffee** [kam193/thbrd-signature#8]
Hey there,

I have installed this addon through Thunderbird (not Github) and I think all the settings are correct, but nothing seems to be actually syncing. I am sure I missed a setting or something.

 LinuxAndCoffee

**Comment by kam193** [comment]
Hey, have you tried clicking on the `Sync now` button in the settings? Do you see a message `Last sync: xxx` in settings?

**Comment by LinuxAndCoffee** [comment]
Hey @kam193 

So I just went back and realized I never connected the plugin to my Google account, so there was nothing to sync with. I am so sorry, not enough coffee or sleep lately. Once I did that, everything works perfectly and I cannot thank you enough for your help!

LinuxAndCoffee

**Comment by kam193** [comment]
No problem - I'm happy it helps you! 

Have a great sleep and tasty coffee ;)
