### ISSUE TITLE
Sync successful but not shown in tbird parameters

### ISSUE THREAD

**Issue by TwiggyWan** [kam193/thbrd-signature#9]
Hello, thanks for the add-on.

I have trouble to make it work.
After install I do manual sync as written : 
![image](https://github.com/kam193/thbrd-signature/assets/5596799/c1ed9c27-690e-4fbf-a6ef-87ec7295d4ee)
I clicked on "connect" on top right, then once i provided my creds I pressed "sync now".

but there's nothing when I look at my account settings : 

![image](https://github.com/kam193/thbrd-signature/assets/5596799/57545bd6-8e1c-4cc0-b734-c09b124390dc)

When I send myself an email the gmail signature is not there.

Do I need to do something else?

FWIW it's a corporate email account and the webmail app gets its signature contents from my organisation and it looks like that on the web: 
![image](https://github.com/kam193/thbrd-signature/assets/5596799/ffba9c8c-8d17-48c2-bca3-c69d58754593)

thanks.

**Comment by TwiggyWan** [comment]
I forgot to select the gmail alias, thought it was not needed :(

![image](https://github.com/kam193/thbrd-signature/assets/5596799/a8734a81-6dd4-4e51-9f9c-1cb8d92882ab)

all good now

**Comment by TwiggyWan** [comment]
I forgot to select the gmail alias name :(

![image](https://github.com/kam193/thbrd-signature/assets/5596799/54dd5e50-91e6-4003-829e-0e3dfd9e1d63)

it's all good now.

**Comment by kam193** [comment]
Ah, great it works :)
